### ISSUE TITLE
Naomi Mobile Suit Gundam Games 

### ISSUE THREAD

**Issue by LegendaryBoyA12** [libretro/flycast#893] opened 2020-05-16 22:04 UTC
While trying to play mobile suit gundam the earth federation vs the principality of Zeon and the Deluxe version, the controls always want to move left. Even after setting the controls in retroarch to none, the game still wants to move left in the in-game menus and the game as if the joystick was stuck. I had tested it with both a joystick and the keyboard layout

**Comment by kage2051** [comment] 2020-05-17 19:23
Are you using a .bin/.lst version? Since they're legacy variants of Naomi dumps and mostly introduce additional bugs that aren't present on the MAME .zip dumps.

**Comment by LegendaryBoyA12** [comment] 2020-05-18 06:30
No, I've made sure to use current versions of the mame  zips. The message saying to update to mame doesnt appear either. As far as the game goes, it seems to run fine except this issue. Other games using naomi dont have this bug on my side. I've also gone into the test menu and checked the input readout, and it registers the joystick movement properly

**Comment by kage2051** [comment] 2020-05-19 17:55
Make sure to keep DIV Matching disabled. That feature is known to break most games, for example in Alien Front it introduces the 'auto-left movement' bug and also makes scope to malfunction in Silent Scope.

**Comment by LegendaryBoyA12** [comment] 2020-05-20 01:25
I made sure to double check that DIV Matching was disabled. I even enabled the option and restarted the core, and both had the same result. I also tested Alien Front, and I'm not getting an issue with that game

**Comment by LegendaryBoyA12** [comment] 2020-05-27 03:05
Just wanted to check if there was anything else I could check or do. This emulator is amazing, and I can't thank you guys enough for the work done

**Comment by flyinghead** [comment] 2020-05-27 15:05
I can reproduce it but I'm still investigating

**Comment by flyinghead** [comment] 2020-05-29 13:48
This should be fixed in the next build

**Closed as completed** 2020-06-14 14:55 UTC
Labels: bug, input bug, naomi
