### ISSUE TITLE
Trigger Heart Exelica - hellish input delay

### ISSUE THREAD

**Issue by daninthemix** [libretro/flycast#761] opened 2019-12-28 13:31 UTC
Not sure if there are any settings that can solve this, but Trigger Heart Exelica has massive input delay (over 3 seconds).

**Comment by Panderner** [comment] 2019-12-28 14:30
Naomi or Dreamcast Version?

**Comment by daninthemix** [comment] 2019-12-28 14:33
Naomi.

**Comment by Panderner** [comment] 2019-12-28 14:53
It's a duplicate of #414

**Comment by flyinghead** [comment] 2019-12-28 16:17
Yes, it’s a known issue. Let’s keep the discussion in #414

**Closed as completed by flyinghead** 2019-12-28 16:17 UTC
