### ISSUE TITLE
LR Flycast glitching under Threaded rendering option

### ISSUE THREAD

**Issue by sergioad** [libretro/flycast#996] opened 2020-12-28 06:22 UTC
Hello friends when playing SFIII on Flycast with the "Threaded rendering" option enabled I am getting lots of issues on my Raspberry pi 4, this issue apparently also aplies in other 2D fighting games like CvS 1, CvS 2 and MvC2

**Comment by barbudreadmon** [comment] 2020-12-28 12:19
dupe of #997

**Closed as completed by barbudreadmon** 2020-12-28 12:19 UTC
