### ISSUE TITLE
Dolphin Blue freeze at first stage ( Odroid N2 TheRA )

### ISSUE THREAD

**Issue by dewenhsu** [libretro/flycast#626] opened 2019-09-07 04:58 UTC
use lr-flycast 0.1 446ec55 on Odroid N2, Dolphin Blue ( both mame zip or .bin format ) will freeze or back to start when play stage 1 about 15 second. 
The continue screen may look strange
https://www.dropbox.com/s/2zd557j3g2tn17l/IMG_0636.JPG?dl=0

**Comment by flyinghead** [comment] 2019-09-19 18:33
Duplicate of #450

**Closed as completed by flyinghead** 2019-09-19 18:33 UTC

**Comment by escenkay** [comment] 2019-09-20 22:02
Any updates on this issue? Would love to finish the game. It keeps freezing on the same spot on the final level.

**Comment by Yobiwan29** [comment] 2020-08-12 07:38
Same freeze at final stage on Retropie 4.6.6 (Pi4). I tried some stuff in naomi service menu, it didn't help.
