### ISSUE TITLE
[Bug]Threaded rendering add 1 frame of input lag in some games

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#863] opened 2020-04-10 18:36 UTC
If you enable threaded rendering, 2 frames of input lag are added.

You can check with frame advance, please try with Threaded Rendering ON & OFF to compare :

- Press P, hold the input (LP), Press K and count how many times until the character moves.

It is present in CVS2, MVC2 & SFA3. 1 frame is added with internal advancing and 1 another frame is added in reality.

My camera capture 2 frames of input lag compared to Threaded OFF

Tested in Win10 + latest RA/Core builds

Issue already opened https://github.com/libretro/flycast/issues/738 for 1 frame

Can somebody else test with a 60 fps camera ? I'm really not sure about the 2nd frame being added and my tests aren't precise.

**Comment by flyinghead** [comment] 2020-04-10 20:22
duplicate of #738

**Closed as completed by flyinghead** 2020-04-10 20:22 UTC
