### ISSUE TITLE
Dolphin Blue freezes in the last phase

### ISSUE THREAD

**Issue by spielvan** [libretro/flycast#728] opened 2019-12-01 23:56 UTC
@flyinghead I don't know why on android Dolphin Blue freezes in the last phase, freezes right after the beginning of the phase, since the first time I tested it always freezes in the same place

**Comment by barbudreadmon** [comment] 2019-12-02 06:21
duplicate of https://github.com/libretro/flycast/issues/450

**Closed as completed by barbudreadmon** 2019-12-02 06:21 UTC
