### ISSUE TITLE
Psyvariar 2 alpha sorting bug with gl backend

### ISSUE THREAD

**Issue by trnzaddict** [libretro/flycast#765] opened 2020-01-01 16:57 UTC
Win7x64, Nvidia 1050ti. As soon as first stage starts, alpha sorting graphic issues begin to happen on any gl backend even when set to “most accurate” alpha sorting in core options.

When core option “Per Triangle Normal” is selected instead, they don’t happen. On Vulkan backend with Alpha Sorting sorting set to “most accurate” graphic glitches do not happen.

**Comment by flyinghead** [comment] 2020-01-04 17:31
This is a regression due to the fix for issue #563, specifically https://github.com/libretro/flycast/commit/ee30a90bceba765245f126cb0229d3edb1b710fb

**Comment by flyinghead** [comment] 2020-01-07 15:08
This should be fixed in the latest core

**Comment by flyinghead** [comment] 2020-01-28 15:40
Resolved

**Closed as completed by flyinghead** 2020-01-28 15:40 UTC
