### ISSUE TITLE
flycast not working now

### ISSUE THREAD

**Issue by elcorsico** [libretro/flycast#578] opened 2019-07-07 09:47 UTC
hi dev , please delete bug in flycast 
now another game dreamcast CE are no working , why
test in X64 v1.7.7 _ Game : sega rally 2.chd

thanks for reply ;-)
tchuss

**Comment by flyinghead** [comment] 2019-07-07 11:06
duplicate of #575

**Comment by flyinghead** [comment] 2019-08-28 14:12
should be fixed by https://github.com/libretro/flycast/commit/b5331915f7b85d025c70b4bc021b4e4fc50f7cff

**Closed as completed by flyinghead** 2019-08-28 14:12 UTC
