### ISSUE TITLE
Dolphin Blue crashes in the last stage

### ISSUE THREAD

**Issue by spielvan** [libretro/flycast#870] opened 2020-04-15 18:55 UTC
Dolphin Blue crashes in the last phase, I tried everything, bin + ist format, rom zip from mame, run and always stop in the same place, at the beginning of the last phase, someone would have a save state of this game passing this part, for me to use in the retroarch?

**Comment by flyinghead** [comment] 2020-04-15 19:13
duplicate of #728 and #450 

message received

**Closed as completed by flyinghead** 2020-04-15 19:13 UTC
