### ISSUE TITLE
DOA 2 crashes during the attract mode.

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/flycast#735] opened 2019-12-13 02:22 UTC
Naomi version crashes at the same spot in the attract mode, a few minutes in, right before it shows the stage with the machinery parts. Can reproduce it every time.

**Comment by barbudreadmon** [comment] 2019-12-13 06:56
Seems like a duplicate of https://github.com/libretro/flycast/issues/184 for me

**Comment by Tasosgemah** [comment] 2019-12-13 16:04
> 
> 
> Seems like a duplicate of #184 for me

You are right, didn't notice because i wasn't talking about the millennium version. Seems the same crash occurs in the regular version then.

**Comment by flyinghead** [comment] 2019-12-14 23:00
Closing in favor of #184

**Closed as completed by flyinghead** 2019-12-14 23:00 UTC
