### ISSUE TITLE
Crash when Alpha Sorting=Per-Pixel

### ISSUE THREAD

**Issue by marcrobledo** [libretro/flycast#914] opened 2020-06-15 06:47 UTC
I've updated the flycast core and now it crashes when Alpha Sorting is set to Per-Pixel and Video Driver is GL (haven't tried with others) in Windows.
Had to reset the whole core settings in `retroarch-core-options.cfg` in order to make it run again.

```
[ERROR] GL: Invalid enum.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] failed_to_start_audio_driver
[libretro ERROR] 00:00:120 libretro/common.cpp:83 E[COMMON]: [GPF]Unhandled access to : 00000000000000b4
```

**Comment by flyinghead** [comment] 2020-06-15 14:15
Probably duplicate of #911 and probably unrelated to alpha sorting.

Does it also crash with the glcore video driver?

**Comment by marcrobledo** [comment] 2020-06-15 15:44
Works fine with glcore video driver.

If this helps: my flycast core was a couple of months old, it started failing (both Dreamcast and Atomiswave when Alpha Sorting was set to Per-Pixel) when I updated today.

**Comment by barbudreadmon** [comment] 2020-06-20 15:44
fixed by https://github.com/libretro/flycast/commit/6b8e40328e5973873a6105a40425555e562b3b99

**Closed as completed by barbudreadmon** 2020-06-20 15:44 UTC
