### ISSUE TITLE
Build on arm64 fails

### ISSUE THREAD

**Issue by ivangotoy** [libretro/flycast#853] opened 2020-04-01 07:41 UTC
Board: Odroid-N2
OS: Debian Buster
gcc version 8.3.0 (Debian 8.3.0-6) 
binutils       2.31.1-16    arm64
no extra CFLAGS set in current environment
command for starting the build: make -j4 platform=odroid-n2
error:
as   -mcpu=cortex-a73 -mtune=cortex-a73.cortex-a53 -DHOST_CPU=0x20000006 -DTARGET_LINUX_ARMv8 -frename-registers -c -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize  -I./core/libretro -I./core/ -I./core/deps -I./core/deps/picotcp/include -I./core/deps/picotcp/modules -I./core/libretro-common/include -I./core/deps/vixl -I./core/deps/flac/include core/rec-ARM64/ngen_arm64.S -o core/rec-ARM64/ngen_arm64.o
Assembler messages:
Error: unrecognized option -mtune=cortex-a73.cortex-a53
make: *** [Makefile:1115: core/rec-ARM64/ngen_arm64.o] Error 1

**Comment by MastaG** [comment] 2020-04-01 13:58
Hi, it seems the compiler in Debian Buster is borked and doesn't support  -mtune=cortex-a73.cortex-a53

Make sure you're using the latest revision (git pull). Then edit the Makefile and remove the " -mtune=cortex-a73.cortex-a53" from lines 436 and 437.

Perhaps it will work then.

**Comment by ivangotoy** [comment] 2020-04-01 15:27
The suggested edit didn't work as expected:

as   -mcpu=cortex-a73 -DHOST_CPU=0x20000006 -DTARGET_LINUX_ARMv8 -frename-registers -c -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize  -I./core/libretro -I./core/ -I./core/deps -I./core/deps/picotcp/include -I./core/deps/picotcp/modules -I./core/libretro-common/include -I./core/deps/vixl -I./core/deps/flac/include core/rec-ARM64/ngen_arm64.S -o core/rec-ARM64/ngen_arm64.o
as: invalid option -- 'H'
make: *** [Makefile:1082: core/rec-ARM64/ngen_arm64.o] Error 1
make: *** Waiting for unfinished jobs....

I suppose it somehow gets the 'H' from -DHOST and interprets it as an option.

**Comment by flyinghead** [comment] 2020-04-01 15:36
I think the issue is that .S files must be compiled with the c compiler on this platform.
This is the part of the Makefile that does it:
```
ifneq (,$(findstring arm, $(ARCH)))
	CC_AS    = ${CC_PREFIX}gcc #The ngen_arm.S must be compiled with gcc, not as
	ASFLAGS  += $(CFLAGS)
endif
```
Try to build with: make -j4 platform=odroid-n2 ARCH=arm

**Comment by ivangotoy** [comment] 2020-04-01 15:56
It worked now (with ARCH=arm triggering the check for the .S file) Content is playable with the compiled binary.

**Comment by flyinghead** [comment] 2020-04-07 15:36
Closing as resolved

**Closed as completed by flyinghead** 2020-04-07 15:36 UTC
