### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#760] opened 2019-12-28 07:00 UTC
delete

**Comment by flyinghead** [comment] 2020-01-01 08:33
Here are some screenshots of actual dreamcast footage for this game:
<img width="1440" alt="Screenshot 2020-01-01 at 09 25 14" src="https://user-images.githubusercontent.com/16261910/71639546-d6d1e900-2c78-11ea-9a84-f9f845ccc423.png">
<img width="1440" alt="Screenshot 2020-01-01 at 09 21 12" src="https://user-images.githubusercontent.com/16261910/71639547-d76a7f80-2c78-11ea-98f1-504ef5a2d27f.png">
I don't see any obvious difference in the bottom left corner but I may be overlooking something.

Regarding the Start menu in airship battles, this is normally fixed by enabling the "Render to texture Buffer" option. It is normally enabled automatically for this game unless it's not recognized. (Are you using a CDI?) Try to force enable this option and see if it helps. See #467.

Regarding audio issues, make sure to enable the DSP as it is required for accurate sound. If that doesn't help, please provide more details so I can reproduce it. Thanks.

**Comment by Apocalypse612** [comment] 2020-01-01 17:34
I'll try these suggestions later tonight. Since I don't real hardware that's functional at the moment, I'm shocked to see that graphical glitch was in the original ROM. My apologies.

**Comment by Apocalypse612** [comment] 2020-01-01 21:40
I'm using a .GDI, and the Render to texture buffer was disabled by default, so I've now turned that on. DSP was already enabled though, so I'll try to see if I can get some captures to show you.

**Closed as completed** 2024-08-24 15:47 UTC
