### ISSUE TITLE
Disc Swap issue in D2

### ISSUE THREAD

**Issue by Rheph** [libretro/flycast#508] opened 2019-03-25 19:18 UTC
Hello, I made a post on the libretro forums regarding this issue and was redirected here.
Basically, my problem pertains to changing from Disc 1 to 2 at the designated swap point in the game _D2._ 

I am able to swap from Disc 1 to 4 successfully to view the Opening Movie (which is on Disc 4, presumably for space conservation reasons), and I am able to swap from any disc back to Disc 1 upon selecting New Game. However, at the end of Disc 1, when the game prompts me to insert Disc 2, I follow the same steps, but the game does not register and I am left stuck on the transition screen. I swap back and forth, I open and close the virtual tray, and still it does not let me proceed.

It may be worth noting that I am also unable to load my Disc 1 save from any other Disc, as I run into the same issue. It asks me to insert Disc 1, I do so, and it does not register.
I have confirmed that this is not a disc-image issue, as all discs boot fine on their own, and I even went so far as to use alternative files. Still no dice.

Further information and links to my VMU files can be found in my original thread here: https://forums.libretro.com/t/reicast-disc-swap-problem-d2/21513/3

Any help would be greatly appreciated. Thank you for reading!

**Comment by flyinghead** [comment] 2019-03-25 23:05
This PR should fix the problem.

You will have to eject the disk, let the game run for a second then switch to the second disk. D2 is picky when detecting a disk change.

**Comment by Rheph** [comment] 2019-03-26 00:36
Great to hear it is fixed!
I'm really inexperienced with GitHub, so could I ask for a quick explanation of how to download the fix? Do I just update the core via Retroarch or is there a link here? Sorry to impose...

**Comment by Rheph** [comment] 2019-03-26 00:47
Thank you for the fix! I just updated the core and tested using your method, and it worked perfectly!
I'm really happy that I can continue in the game now, thanks again!

**Comment by flyinghead** [comment] 2019-03-26 06:05
If the problem is fixed, you can close this issue.

Thanks

**Closed as completed** 2019-03-26 13:15 UTC
