### ISSUE TITLE
Boot to Bios screen has no picture in it.

### ISSUE THREAD

**Issue by Testsr** [libretro/flycast#751] opened 2019-12-21 11:10 UTC
Using RetroArch 1.8.1, Windows, Intel Graphics, Vulcan. Trying to boot up Sonic Adventure [Europe].
![Bios](https://user-images.githubusercontent.com/31809837/71307178-9edbd200-243e-11ea-8439-b4bd6d10e015.png)

**Comment by flyinghead** [comment] 2019-12-21 12:21
This could be an Intel driver bug. Setting the Alpha Sorting core option to Per-strip is a work-around but may produce graphical glitches.

It seems the Intel driver disables (and fails) the depth test if depth buffer writes are disabled.

**Comment by flyinghead** [comment] 2019-12-21 12:23
This is a duplicate of #750 so closing this one

**Closed as completed by flyinghead** 2019-12-21 12:23 UTC
